version: "3.8"

services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=alfidodb
      - DB_USER=alfido
      - DB_PASSWORD=alfido123
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=alfidodb
      - POSTGRES_USER=alfido
      - POSTGRES_PASSWORD=alfido123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
